import type { Service, Location, Testimonial } from "@/types";

export const services: Service[] = [
  {
    id: "traditional-locs",
    name: "Traditional Locs",
    description: "Hand-crafted starter locs with precision parting and expert twisting for a natural, timeless look.",
    price: "From $250",
    duration: "3-5 hours",
    category: "locs",
    featured: true,
  },
  {
    id: "loc-retwist",
    name: "Loc Retwist & Style",
    description: "Maintain your locs with our signature retwist technique, including scalp treatment and styling.",
    price: "From $120",
    duration: "1.5-2.5 hours",
    category: "locs",
  },
  {
    id: "faux-locs",
    name: "Faux Locs",
    description: "Achieve the loc aesthetic with our premium faux locs, available in multiple lengths and textures.",
    price: "From $300",
    duration: "4-6 hours",
    category: "locs",
    featured: true,
  },
  {
    id: "knotless-braids",
    name: "Knotless Box Braids",
    description: "Gentle, tension-free braids that protect your natural hair while delivering a flawless finish.",
    price: "From $280",
    duration: "4-7 hours",
    category: "braids",
    featured: true,
  },
  {
    id: "fulani-braids",
    name: "Fulani Braids",
    description: "Cultural elegance meets modern styling with intricate Fulani-inspired braiding patterns.",
    price: "From $220",
    duration: "3-5 hours",
    category: "braids",
  },
  {
    id: "cornrows",
    name: "Cornrows & Feed-Ins",
    description: "Classic cornrow styles from sleek straight-backs to creative artistic patterns.",
    price: "From $150",
    duration: "2-4 hours",
    category: "braids",
  },
  {
    id: "custom-wig",
    name: "Custom Wig Construction",
    description: "Bespoke wigs crafted to your specifications using premium human hair for an undetectable finish.",
    price: "From $500",
    duration: "Consultation required",
    category: "wigs",
    featured: true,
  },
  {
    id: "wig-install",
    name: "Wig Installation",
    description: "Seamless wig application with lace customization, bleaching, and styling for a natural look.",
    price: "From $180",
    duration: "1.5-2 hours",
    category: "wigs",
  },
  {
    id: "silk-press",
    name: "Silk Press",
    description: "Achieve silky-smooth, straightened natural hair with our heat-protective silk press treatment.",
    price: "From $150",
    duration: "1.5-2 hours",
    category: "styling",
  },
  {
    id: "deep-conditioning",
    name: "Deep Conditioning Treatment",
    description: "Intensive moisture and protein therapy to restore strength, shine, and elasticity to your hair.",
    price: "From $80",
    duration: "45 min - 1 hour",
    category: "treatments",
  },
];

export const locations: Location[] = [
  {
    id: "ottawa",
    name: "The Esperience Ottawa",
    city: "Ottawa",
    slug: "ottawa",
    address: "123 Rideau Street, Ottawa, ON K1N 5Y3",
    phone: "(613) 555-0199",
    email: "ottawa@theesperience.com",
    hours: {
      "Monday": "Closed",
      "Tuesday - Friday": "9:00 AM - 7:00 PM",
      "Saturday": "9:00 AM - 6:00 PM",
      "Sunday": "10:00 AM - 4:00 PM",
    },
    coordinates: { lat: 45.4215, lng: -75.6972 },
    isHQ: true,
  },
  {
    id: "montreal",
    name: "The Esperience Montréal",
    city: "Montréal",
    slug: "montreal",
    address: "456 Rue Sainte-Catherine O, Montréal, QC H3B 1A2",
    phone: "(514) 555-0299",
    email: "montreal@theesperience.com",
    hours: {
      "Monday": "Closed",
      "Tuesday - Friday": "9:00 AM - 7:00 PM",
      "Saturday": "9:00 AM - 6:00 PM",
      "Sunday": "10:00 AM - 4:00 PM",
    },
    coordinates: { lat: 45.5017, lng: -73.5673 },
  },
  {
    id: "nyc",
    name: "The Esperience NYC",
    city: "New York City",
    slug: "nyc",
    address: "789 Fulton Street, Brooklyn, NY 11238",
    phone: "(718) 555-0399",
    email: "nyc@theesperience.com",
    hours: {
      "Monday": "Closed",
      "Tuesday - Friday": "10:00 AM - 8:00 PM",
      "Saturday": "9:00 AM - 7:00 PM",
      "Sunday": "10:00 AM - 5:00 PM",
    },
    coordinates: { lat: 40.6826, lng: -73.9656 },
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Amara J.",
    location: "Ottawa",
    text: "The Esperience completely transformed my locs. The attention to detail and the luxurious atmosphere made me feel like royalty. I won't go anywhere else.",
    rating: 5,
    service: "Traditional Locs",
  },
  {
    id: "t2",
    name: "Nadia K.",
    location: "Montréal",
    text: "My knotless braids lasted over two months and looked stunning the entire time. The stylists here truly understand Black hair.",
    rating: 5,
    service: "Knotless Box Braids",
  },
  {
    id: "t3",
    name: "Zara M.",
    location: "New York City",
    text: "I flew from Atlanta just for their custom wig service. Worth every mile. The craftsmanship is unmatched.",
    rating: 5,
    service: "Custom Wig Construction",
  },
  {
    id: "t4",
    name: "Keisha R.",
    location: "Ottawa",
    text: "From the moment I walked in, I knew this was different. The ambiance, the skill, the care — it's not just a salon, it's an experience.",
    rating: 5,
    service: "Silk Press",
  },
  {
    id: "t5",
    name: "Tanya L.",
    location: "Montréal",
    text: "Best faux locs I've ever had. Lightweight, natural-looking, and absolutely gorgeous. My stylist was an artist.",
    rating: 5,
    service: "Faux Locs",
  },
];
